name: 2 Build and Push image to ACR

# Controls when the workflow will run
on: workflow_dispatch

env:
  ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
  IMAGE_NAME: oapi
  #tag: ${{ github.sha }}
  TAG: 7999

jobs:
  # This workflow contains a job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Create ACR
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az acr build -t $ACR_REGISTRY/$IMAGE_NAME:$TAG -r $ACR_REGISTRY
