# This is a basic workflow to help you get started with Actions

name: 3 Deploy PoC Env

# Controls when the workflow will run
on: [workflow_dispatch]

env:
  APP_ID: ${{ secrets.CLIENTID }}
  SP_PWD: ${{ secrets.CLIENTSECRET }}
  TENANT_ID: ${{ secrets.TENANTID }}
  CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME }}
  REGISTRY_SERVER: ${{ secrets.CONTAINER_REGISTRY }}
  REGISTRY_USERNAME: ${{ secrets.ACR_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RG }}
  CONTAINERAPPS_ENVIRONMENT: ${{ secrets.CONTAINERAPPS_ENVIRONMENT }}
  LOCATION: eastus2
  CONTAINER_APP_NAME: oapiwf


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploying-api-env:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: PoC
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp env create --name $CONTAINERAPPS_ENVIRONMENT --resource-group $RESOURCE_GROUP --location $LOCATION
            az containerapp create --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP --image $CONTAINER_IMAGE_NAME --environment $CONTAINERAPPS_ENVIRONMENT --registry-server $REGISTRY_SERVER --registry-username $REGISTRY_USERNAME --registry-password $REGISTRY_PASSWORD --ingress external --target-port 7999 --query properties.configuration.ingress.fqdn --min-replicas 1 --max-replicas 10 --cpu 0.25 --memory 0.5Gi
