# This is a basic workflow to help you get started with Actions

name: Deploy API to Container App

# Controls when the workflow will run
on: workflow_dispatch

env:
  APP_ID: ${{ secrets.CLIENTID }}
  SP_PWD: ${{ secrets.CLIENTSECRET }}
  TENANT_ID: ${{ secrets.TENANTID }}
  CONTAINER_IMAGE_NAME: acraksworkshop.azurecr.io/oapi:7999
  REGISTRY_SERVER: ${{ secrets.CONTAINER_REGISTRY }}
  REGISTRY_USERNAME: ${{ secrets.ACR_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp create --name my-container-app --resource-group $RESOURCE_GROUP --image $CONTAINER_IMAGE_NAME --environment $CONTAINERAPPS_ENVIRONMENT --registry-server $REGISTRY_SERVER --registry-username $REGISTRY_USERNAME --registry-password $REGISTRY_PASSWORD
